services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
#      - chatbot
      - mongodb
#      - queue
#
#  chatbot:
#    build: ./chatbot
#    depends_on:
#      - queue
#
#  queue:
#    image: rabbitmq:3-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017

volumes:
  mongo_data:
